# Generated by Django 4.0.4 on 2025-03-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_part', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
